import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ScrollBackground from "@/components/ScrollBackground";
import "./globals.css";
import "animate.css";
import { Maven_Pro } from "next/font/google";

const mavenPro = Maven_Pro({
  weight: ["400", "500", "600", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Isfhan Ahmed",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1, maximum-scale=5",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${mavenPro.className} relative min-h-screen`}>
        {/* Scroll-based Background */}
        <ScrollBackground />

        <div className="relative z-10">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
